# Generated by Django 4.1.6 on 2023-03-25 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moneytransfer',
            old_name='enter_destination_email',
            new_name='enter_destination_username',
        ),
        migrations.RemoveField(
            model_name='moneytransfer',
            name='enter_points_to_transfer',
        ),
        migrations.AddField(
            model_name='moneytransfer',
            name='enter_amount_to_transfer',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
