# Generated by Django 4.1.6 on 2023-03-25 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_rename_enter_destination_email_moneytransfer_enter_destination_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionhistory',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
