# Generated by Django 4.1.6 on 2023-03-25 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_transactionhistory_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneytransfer',
            name='enter_amount_to_transfer',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='transactionhistory',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
