# Generated by Django 4.1.6 on 2023-04-01 15:51

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_alter_balance_balance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactionhistory',
            old_name='transactionType',
            new_name='transaction_type',
        ),
        migrations.AddField(
            model_name='transactionhistory',
            name='clearing_balance',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactionhistory',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 4, 1, 15, 51, 24, 549799, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactionhistory',
            name='to_from',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
    ]
