# Generated by Django 4.1.6 on 2023-04-01 16:17

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactions', '0008_delete_transactionhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_from', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('transaction_type', models.CharField(choices=[('sent', 'Sent'), ('received', 'Received')], max_length=8)),
                ('amount', models.PositiveIntegerField()),
                ('clearing_balance', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)])),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
