# Generated by Django 4.1.6 on 2023-04-02 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_transactionhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneytransfer',
            name='enter_comment',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactionhistory',
            name='comment',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
