# Generated by Django 4.1.6 on 2023-04-02 09:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0010_moneytransfer_enter_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionhistory',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 4, 1, 10, 56, 57, 309848)),
            preserve_default=False,
        ),
    ]
