# Generated by Django 4.1.6 on 2023-04-02 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0011_transactionhistory_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionhistory',
            name='clearing_balance',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='transactionhistory',
            name='comment',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
