# Generated by Django 4.1.6 on 2023-04-06 15:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0013_alter_balance_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionhistory',
            name='clearing_balance',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
