# Generated by Django 4.1.6 on 2023-04-06 15:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0014_alter_transactionhistory_clearing_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneytransfer',
            name='enter_amount_to_transfer',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)]),
        ),
    ]
