# Generated by Django 4.1.6 on 2023-04-05 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency_exchange', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyexchange',
            name='convert_from',
            field=models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP')], max_length=3),
        ),
        migrations.AlterField(
            model_name='currencyexchange',
            name='convert_to',
            field=models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP')], max_length=3),
        ),
    ]
