# Generated by Django 4.1.6 on 2023-04-06 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency_exchange', '0007_alter_currencyexchange_convert_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyexchange',
            name='convert_from',
            field=models.CharField(choices=[('EUR', 'EUR'), ('GBP', 'GBP'), ('USD', 'USD')], max_length=3),
        ),
        migrations.AlterField(
            model_name='currencyexchange',
            name='convert_to',
            field=models.CharField(choices=[('EUR', 'EUR'), ('GBP', 'GBP'), ('USD', 'USD')], max_length=3),
        ),
    ]
