# Generated by Django 4.1.6 on 2023-03-25 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='balance',
            old_name='emailID',
            new_name='name',
        ),
    ]
