# Generated by Django 4.1.6 on 2023-03-25 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_rename_emailid_balance_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=4),
        ),
    ]
