# Generated by Django 4.1.6 on 2023-03-26 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_alter_balance_balance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Balance',
        ),
    ]
