# Generated by Django 4.1.6 on 2023-04-04 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='request_to_email',
            field=models.CharField(choices=[('kshitijpathak1996@gmail.com', 'kshitijpathak1996@gmail.com'), ('user1@gmail.com', 'user1@gmail.com'), ('user2@gmail.com', 'user2@gmail.com'), ('user3@gmail.com', 'user3@gmail.com'), ('doshiomkar68@gmail.com', 'doshiomkar68@gmail.com')], max_length=30),
        ),
    ]
