# Generated by Django 4.1.6 on 2023-04-04 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notifications_request_to_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notifications',
            old_name='request_to_email',
            new_name='email',
        ),
        migrations.AlterField(
            model_name='notifications',
            name='message',
            field=models.CharField(max_length=500),
        ),
    ]
