# Generated by Django 4.1.6 on 2023-04-04 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_rename_request_to_email_notifications_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='email',
            field=models.CharField(max_length=30),
        ),
    ]
