# Generated by Django 4.1.6 on 2023-04-06 15:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_notifications_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='request_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)]),
        ),
    ]
